add new directories and files
Caren-Koroeny/BookStore pull request #2
Opened 2023-03-06 13:01 UTC by Caren-Koroeny

- Add Redux Toolkit `(npm install react-redux @reduxjs/toolkit)`.
 
- Create a directory that will contain all your Redux logic `(/src/redux)`.

- Configure a Redux store `(/src/redux/store.js)`

2023-03-06 18:02 UTC, muneebulrehman requested changes
Hi @Caren-Koroeny , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR

## Required Changes ♻️
_Check the comments under the review._

- [ ] I would recommend removing the Microverse badge that you have included in the README 
![image](https://user-images.githubusercontent.com/33268927/223193071-d42b48f7-46ee-4dad-bfa2-afe2bf890011.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-06 18:02 UTC, muneebulrehman commented on src/redux/books/bookSlice.js
> +export { BookReducer, AddBook, RemoveBook };
Kindly use the `createSlice` function to automatically generate action creators and action types that will correspond to the reducers and state. I see you have used `createSlice` in categoriesSlice.js`. I recommend you follow the same approach here. Remember to export the reducer actions once you create them.

2023-03-07 05:24 UTC, Caren-Koroeny commented on src/redux/books/bookSlice.js
> +export { BookReducer, AddBook, RemoveBook };
Okay, I fixed it, thank you for the corrections.

![Screenshot from 2023-03-07 08-23-12](https://user-images.githubusercontent.com/55842414/223328121-e7714c0c-3cbb-4c07-a953-fc365f0e59cf.png)

2023-03-07 05:54 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 06:42 UTC, merged